[package]
name = "fechatter-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
tower-http = { workspace = true }
argon2 = { version = "0.5", features = ["std"] }
dotenv = "0.15"
jsonwebtoken = "9.1"
once_cell = "1.21"
validator = { version = "0.20.0", features = ["derive"] }
async-trait = "0.1"
tower = "0.5.2"
lazy_static = "1.5.0"
dashmap = "6.1.0"


[dev-dependencies]
sqlx-db-tester = "0.6.0"
http-body-util = "0.1.3"
