[package]
name = "fechatter-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["cookie"] }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = "0.1.15"
futures = { workspace = true }
chrono = { workspace = true }
tower-http = { workspace = true }
argon2 = { version = "0.5", features = ["std"] }
dotenv = "0.15"
jsonwebtoken = "9.1"
once_cell = "1.18"
validator = { version = "0.20.0", features = ["derive"] }
async-trait = "0.1"
tower = "0.5.2"
lazy_static = "1.5.0"
dashmap = "6.1.0"
sha1 = "0.10.6"
sha2 = "0.10.7"
hex = "0.4.3"
rand = "0.9.1"
mime_guess = "2.0.5"
http-body-util = "0.1.3"
hyper = "1.6.0"
bytes = "1.10.1"
mockall = { version = "0.13.1", default-features = false }


[dev-dependencies]
sqlx-db-tester = "0.6.0"
http-body-util = "0.1.3"
