[server]
host = "0.0.0.0"
port = 6688
base_dir = "./uploads"
db_url = "postgres://localhost/fechatter_db"

[auth]
jwt_secret = "your-jwt-secret-key-please-change-in-production"
audience = "fechatter-web" 
issuer = "fechatter-server"
token_lifetime = 1800  # 30 minutes
refresh_token_lifetime = 2592000  # 30 days 