### Variables
@baseUrl = http://localhost:6688

### signup
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
  "fullname": "Alice",
  "email": "alice@acmn.com",
  "password": "password"
}

### signin
# @name login
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
  "email": "alice@acmn.com",
  "password": "password"
}

### Use the token from the login response
@authToken = {{login.response.body.token}}

### signin(invalid user)
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
  "email": "bob@acmn.com",
  "password": "password"
}

### signin(invalid password)
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
  "email": "alice@acmn.com",
  "password": "invalid"
}

### list chats
GET {{baseUrl}}/api/chat
Authorization: Bearer {{authToken}}

### create chat
POST {{baseUrl}}/api/chat
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Test Chat",
  "description": "This is a test chat"
}

### update chat
PATCH {{baseUrl}}/api/chat/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Updated Chat",
  "description": "This is an updated test chat"
}

### delete chat
DELETE {{baseUrl}}/api/chat/1
Authorization: Bearer {{authToken}}

### send message
POST {{baseUrl}}/api/chat/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Hello, this is a test message"
}

### list messages
GET {{baseUrl}}/api/chat/1/messages
Authorization: Bearer {{authToken}}
