apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- redis.yaml
- nats.yaml
- meilisearch.yaml
- clickhouse.yaml
- fechatter-server.yaml
- notify-server.yaml
- bot-server.yaml
- analytics-server.yaml
- gateway.yaml

commonLabels:
  app.kubernetes.io/name: fechatter
  app.kubernetes.io/part-of: fechatter-platform