version: '3.8'

networks:
  fechatter-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  nats-data:
  meilisearch-data:
  clickhouse-data:

services:
  # Core Application Services
  fechatter-server:
    image: nrt.vultrcr.com/fechatter/server:latest
    container_name: fechatter-server
    restart: unless-stopped
    ports:
      - "6688:6688"
    networks:
      - fechatter-network
    volumes:
      - /app/config:/app/config:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6688/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  analytics-server:
    image: nrt.vultrcr.com/fechatter/analytics:prod
    container_name: analytics-server
    restart: unless-stopped
    ports:
      - "6690:6690"
    networks:
      - fechatter-network
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6690/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notify-server:
    image: nrt.vultrcr.com/fechatter/notify:prod
    container_name: notify-server
    restart: unless-stopped
    ports:
      - "6687:6687"
    networks:
      - fechatter-network
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6687/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot-server:
    image: nrt.vultrcr.com/fechatter/bot:prod
    container_name: bot-server
    restart: unless-stopped
    ports:
      - "6686:6686"
    networks:
      - fechatter-network
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6686/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Infrastructure Services
  postgres:
    image: pgvector/pgvector:pg17
    container_name: fechatter-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - fechatter-network
    environment:
      POSTGRES_USER: fechatter
      POSTGRES_PASSWORD: fechatter_password
      POSTGRES_DB: fechatter
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fechatter -d fechatter"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fechatter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fechatter-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nats:
    image: nats:2.10-alpine
    container_name: fechatter-nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - fechatter-network
    volumes:
      - nats-data:/data
    command: ["--jetstream", "--store_dir=/data"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: fechatter-meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    networks:
      - fechatter-network
    volumes:
      - meilisearch-data:/meili_data
    environment:
      MEILI_MASTER_KEY: fechatter_search_key
      MEILI_ENV: production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: fechatter-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - fechatter-network
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: fechatter_analytics
      CLICKHOUSE_USER: fechatter
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3 