# Fly.io configuration for Prometheus monitoring service
app = "fechatter-monitoring"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile.monitoring"

[env]
  # Prometheus configuration
  PROMETHEUS_RETENTION_TIME = "15d"
  PROMETHEUS_RETENTION_SIZE = "10GB"

[experimental]
  # Enable private networking to access other Fechatter services
  private_network = true

# Mount persistent volume for Prometheus data
[mounts]
  source = "prometheus_data"
  destination = "/prometheus"

# HTTP service for Prometheus
[[services]]
  http_checks = []
  internal_port = 9090
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  
  # Public HTTPS endpoint (optional, for direct access)
  [[services.ports]]
    handlers = ["http"]
    port = 80
    
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  
  # Health check
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"