# rust-analyzer.toml - Configuration for rust-analyzer
# This file configures rust-analyzer to only check the fechatter_server crate

# Check configuration controls how cargo check is performed
[check]
# Use "check" command (could also be "clippy" if you prefer)
command = "check"

# This is the most important setting:
# Passes --package fechatter_server to cargo check
# This restricts checking to only the fechatter_server package
extraArgs = ["--package", "fechatter_server"]

# Don't check test targets, examples, etc. to improve performance
# Set to true if you want to include tests in the analysis
allTargets = false

# Explicitly ignore specific directories/crates
# This is redundant with the package specification above,
# but provides an extra layer of exclusion to be certain
ignore = ["fechatter_frontend/"]

# Cargo configuration
[cargo]
# Enable all features when analyzing code
# You can change this to specific features if needed
features = "all"

# Enable build scripts processing which is necessary for many crates
buildScripts.enable = true

# Enable procedural macro support
[procMacro]
enable = true

# Explicitly specify which project(s) to analyze
# This further restricts rust-analyzer to only work with the fechatter_server crate
[linkedProjects]
paths = ["fechatter_server/Cargo.toml"]

