# Fechatter Server Configuration Example
# 复制此文件为 config.toml 并根据需要修改

[environment]
# 环境类型: development, testing, staging, production
type = "development"

[server]
host = "127.0.0.1"
port = 8080
workers = 4
tls_enabled = false
# tls_cert_path = "/path/to/cert.pem"
# tls_key_path = "/path/to/key.pem"
shutdown_timeout = "30s"

[database]
url = "postgresql://localhost/fechatter_dev"
max_connections = 20
min_connections = 5
connect_timeout = "30s"
idle_timeout = "600s"
max_lifetime = "3600s"
ssl_enabled = false
# ssl_cert_path = "/path/to/ca-cert.pem"
query_logging = true
slow_query_threshold = "1s"
pool_monitoring = true
database_name = "fechatter_dev"
auto_migrate = true

[auth]
jwt_secret = "your-super-secret-jwt-key-change-this-in-production"
access_token_expiry = "15m"
refresh_token_expiry = "7d"
remember_me_enabled = true
remember_me_expiry = "30d"
password_min_length = 8
password_require_special = true
password_require_number = true
password_require_uppercase = true
max_login_attempts = 5
account_lockout_duration = "15m"
two_factor_enabled = false
session_timeout = "24h"

[cache]
ttl = "300s"
cache_private = false
user_specific = false
max_size = 104857600     # 100MB
key_prefix = "fechatter"
compress = true
variants = []

[rate_limit]
window = "60s"
max_requests = 100
key_prefix = "rate_limit"
strategy = "FixedWindow"
burst_enabled = false
burst_capacity = 0

[middleware]
request_id_enabled = true
server_time_enabled = true
compression_enabled = true
compression_level = 6
cors_enabled = true
cors_origins = ["http://localhost:3000"]
request_logging_enabled = true
response_time_enabled = true
security_headers_enabled = false
request_body_limit = 16777216            # 16MB
request_timeout = "30s"
cache_enabled = true
rate_limit_enabled = true
auth_enabled = true

[logging]
level = "debug"
structured = false
format = "Pretty"
# file_path = "/var/log/fechatter/app.log"
rotation_enabled = false
max_file_size = 0
max_files = 0

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_enabled = true
health_check_path = "/health"
tracing_enabled = true
tracing_sample_rate = 1.0
