[package]
name = "fechatter_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.11", features = ["v4", "v7", "serde"] }
tower = { version = "0.5", features = ["util", "timeout", "limit"] }

# HTTP and API testing
reqwest = { version = "0.12", features = ["json", "stream", "multipart"] }
axum = { version = "0.8.4", features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["cookie", "typed-header"] }
futures = "0.3"
reqwest-eventsource = "0.6"

# Database testing
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "time", "json", "migrate", "macros", "chrono"] }
sqlx-db-tester = "0.6.0"

# NATS testing
async-nats = { version = "0.41.0" }
tokio-stream = { workspace = true }
async-stream = "0.3"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Test utilities
tempfile = "3.10"
md5 = "0.7"
base64 = "0.22"

# Local project dependencies
fechatter_core = { workspace = true }
fechatter_server = { path = "../fechatter_server", features = ["test-util"] }
notify_server = { workspace = true }

# Additional dependencies
log = "0.4"
async-trait = "0.1"
cookie = "0.17"
http-body-util = "0.1"
jwt-simple = "0.12.8"
nanoid = "0.4"
once_cell = "1.19"
redis = { version = "0.23", features = ["tokio-comp"] }
sha2 = "0.10"
thiserror = "1.0"
time = "0.3"
tower-http = { version = "0.6", features = ["full"] }
hyper = "1.0"
urlencoding = "2.1"
