# Enable unstable Cargo features for Rust Edition 2024
cargo-features = ["edition2024"]

[package]
name = "fechatter_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0.1", features = ["full"] }
quote = "1.0"
