# Notify Server Configuration - Docker Environment
# Production-ready notification service configuration

# Server configuration
server:
  port: 7788
  db_url: "postgresql://fechatter_user:fechatter_pass@postgres:5432/fechatter_db"
  request_timeout_ms: 30000

# JWT Authentication
auth:
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAn/6c0O9F6Cq7aG8l6J0k1qM4+hfWrQZqbYnJp8xBYpU=
    -----END PUBLIC KEY-----
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIP/S+etN7RQJctehWKkdjgnrtQ0AUDIMkCnYS4Zk8RFR
    -----END PRIVATE KEY-----
  token_expiration: 1800 # 30 minutes

# NATS messaging configuration
messaging:
  enabled: true
  provider: "nats"
  nats:
    url: "nats://nats:4222"
    auth:
      enabled: false
    subscription_subjects:
    - "fechatter.notifications.*"
    - "fechatter.user.events"
    - "fechatter.chat.events"
    - "fechatter.message.events"
    # JetStream configuration
    jetstream:
      enabled: true
      stream: "NOTIFICATIONS"
      storage: "file"
      max_bytes: 1073741824 # 1GB
      max_msg_size: 1048576 # 1MB
      max_age: 86400 # 24 hours

      # Consumer configurations
      consumers:
        notification_processor:
          name: "notification-processor"
          filter_subjects:
          - "fechatter.notifications.send"
          - "fechatter.notifications.broadcast"
          ack_wait: "30s"
          max_deliver: 3
          max_batch: 100
          idle_heartbeat: "5s"

        realtime_processor:
          name: "realtime-processor"
          filter_subjects:
          - "fechatter.user.online"
          - "fechatter.user.offline"
          - "fechatter.chat.typing"
          ack_wait: "10s"
          max_deliver: 2
          max_batch: 50
          idle_heartbeat: "3s"

# Search configuration (MeiliSearch)
search:
  enabled: true
  provider: "meilisearch"
  meilisearch:
    url: "http://meilisearch:7700"
    api_key: "fechatter_search_key"
    connection_timeout_ms: 5000
    request_timeout_ms: 30000

    # Index configurations
    indexes:
      messages:
        name: "messages"
        primary_key: "id"
        searchable_fields:
        - "content"
        - "user_name"
        - "chat_name"
        displayed_fields:
        - "id"
        - "content"
        - "user_name"
        - "chat_name"
        - "created_at"
        filterable_fields:
        - "chat_id"
        - "user_id"
        - "created_at"
        sortable_fields:
        - "created_at"

    # Search settings
    settings:
      pagination_limit: 100

# Notification configuration
notification:
  delivery:
    web:
      enabled: true
      sse_enabled: true
      connection_timeout_ms: 60000
      heartbeat_interval_ms: 30000

# Analytics configuration
analytics:
  enabled: true
  endpoint: "http://analytics-server:9091"
  batch_size: 100
  flush_interval_seconds: 30
  timeout_seconds: 10
  use_grpc: false

# Security configuration
security:
  hmac_secret: "fechatter_notify_hmac_secret_key_2024"
  verify_signatures: true
