# Notify Server - 日本地区优化配置
# 实时通知服务，针对200日活用户优化
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-server
  namespace: fechatter
  labels:
    app: notify-server
    version: v1
    region: japan
spec:
  replicas: 2  # 2个副本处理SSE连接
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: notify-server
  template:
    metadata:
      labels:
        app: notify-server
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - notify-server
              topologyKey: kubernetes.io/hostname
      containers:
      - name: notify-server
        image: ghcr.io/your-org/fechatter/notify_server:latest
        ports:
        - containerPort: 6687
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REGION
          value: "japan"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: timezone-config
              key: TZ
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_URL
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: RUST_LOG
          value: "info,notify_server=debug"
        # 实时通知特定配置
        - name: MAX_SSE_CONNECTIONS
          value: "200"       # 支持200个SSE连接(对应日活用户)
        - name: CONNECTION_TIMEOUT
          value: "300s"      # 5分钟连接超时
        - name: HEARTBEAT_INTERVAL
          value: "30s"       # 30秒心跳
        - name: MESSAGE_BUFFER_SIZE
          value: "1000"      # 消息缓冲区大小
        - name: WORKER_THREADS
          value: "2"         # 2个worker线程
        - name: BLOCKING_THREADS
          value: "4"         # 4个阻塞线程
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 400m        # SSE连接需要较少CPU
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 6687
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 6687
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]  # 给SSE连接时间优雅关闭
---
apiVersion: v1
kind: Service
metadata:
  name: notify-server
  namespace: fechatter
  labels:
    app: notify-server
spec:
  type: ClusterIP
  ports:
  - port: 6687
    targetPort: 6687
    protocol: TCP
    name: http
  selector:
    app: notify-server
  sessionAffinity: ClientIP  # SSE连接需要会话亲和性
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300    # 5分钟会话超时
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notify-server-hpa
  namespace: fechatter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notify-server
  minReplicas: 2   # 最低2个副本保证SSE连接稳定
  maxReplicas: 6   # 最高6个副本
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600  # SSE服务扩缩容要更保守
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120