FROM scratch

# Copy the statically compiled binary
COPY target/main/x86_64-unknown-linux-musl/release/notify_server /notify_server

# Set the entrypoint
ENTRYPOINT ["/notify_server"]

# Expose the default port
EXPOSE 6687 