server:
  port: 6687
  db_url: "postgres://fechatter:fechatter_password@postgres:5432/fechatter"
  request_timeout_ms: 30000

auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIP/S+etN7RQJctehWKkdjgnrtQ0AUDIMkCnYS4Zk8RFR
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAMnnmEdL53E3O5UTdVW/VEs9qT6To/48iU7jWpKuVb2c=
    -----END PUBLIC KEY-----
  token_expiration: 86400

messaging:
  enabled: true
  provider: "nats"
  nats:
    url: "nats://nats:4222"
    auth:
      enabled: false
    subscription_subjects:
    - "fechatter.messages.created"
    - "fechatter.chats.member.joined"
    - "fechatter.chats.member.left"
    - "fechatter.realtime.>"
    - "fechatter.broadcast"
    jetstream:
      enabled: true
      stream: "fechatter_events"
      storage: "file"
      max_bytes: 524288000 # 500MB (increased for real-time hot path)
      max_msg_size: 262144 # 256KB
      max_age: 12 # 12 hours retention (optimized for real-time notifications)
      # Unified consumer configuration - single consumer handles all events
      consumers:
        notification_processor:
          name: "unified_processor"
          filter_subjects:
          - "fechatter.messages.created"
          - "fechatter.chats.member.joined"
          - "fechatter.chats.member.left"
          - "fechatter.realtime.>"
          - "fechatter.broadcast"
          ack_wait: "30s"
          max_deliver: 3
          max_batch: 1
          idle_heartbeat: "60s"

search:
  enabled: false
  provider: "meilisearch"
  meilisearch:
    url: "http://meilisearch:7700"
    api_key: ""
    connection_timeout_ms: 3000
    request_timeout_ms: 5000
    indexes:
      messages:
        name: "fechatter_messages"
        primary_key: "id"
        searchable_fields: [ "content" ]
        displayed_fields: [ "id", "chat_id", "sender_id", "content", "created_at" ]
        filterable_fields: [ "chat_id", "sender_id", "created_at" ]
        sortable_fields: [ "created_at" ]
    settings:
      pagination_limit: 50

notification:
  delivery:
    web:
      enabled: true
      sse_enabled: true
      connection_timeout_ms: 30000
      heartbeat_interval_ms: 25000

# Analytics configuration for tracking user behavior
analytics:
  enabled: true
  nats_url: "nats://nats:4222"
  subject_prefix: "fechatter.analytics.notify"
  batch_size: 100
  flush_interval_ms: 5000
