
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fechatter-server
  namespace: fechatter
  labels:
    app: fechatter-server
    version: v1
    region: japan
spec:
  replicas: 3  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fechatter-server
  template:
    metadata:
      labels:
        app: fechatter-server
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fechatter-server
              topologyKey: kubernetes.io/hostname
      containers:
      - name: fechatter-server
        image: ghcr.io/your-org/fechatter/fechatter_server:latest
        ports:
        - containerPort: 6688
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REGION
          value: "japan"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: timezone-config
              key: TZ
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fechatter-secrets
              key: jwt-secret
        - name: RUST_LOG
          value: "info,fechatter_server=debug"
        - name: MAX_CONNECTIONS
          value: "50"  
        - name: POOL_SIZE
          value: "15"  
        - name: WORKER_THREADS
          value: "4"    
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 800m   
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 6688
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 6688
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: fechatter-server
  namespace: fechatter
  labels:
    app: fechatter-server
spec:
  type: ClusterIP
  ports:
  - port: 6688
    targetPort: 6688
    protocol: TCP
    name: http
  selector:
    app: fechatter-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fechatter-server-hpa
  namespace: fechatter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fechatter-server
  minReplicas: 2   
  maxReplicas: 8   
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60